{% set version = '0.1.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-jshintr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/jshintr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/jshintr/jshintr_{{ version }}.tar.gz
  sha256: cd5b9577824c89b4673aa94541f78c73960f8b44748b8bcf33d0a5a504434222

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-htmltools
    - r-htmlwidgets
    - r-rstudioapi
  run:
    - r-base
    - r-htmltools
    - r-htmlwidgets
    - r-rstudioapi

test:
  commands:
    - $R -e "library('jshintr')"           # [not win]
    - "\"%R%\" -e \"library('jshintr')\""  # [win]

about:
  home: https://github.com/stla/jshintr
  license: GPL-3.0-only
  summary: Allow to run 'jshint' on 'JavaScript' files with a 'R' command or a 'RStudio' addin.
    The report appears in the 'RStudio' viewer pane.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'
# Type: Package

extra:
  recipe-maintainers:
    - conda-forge/r
    - thewchan

# Package: jshintr
# Title: Lint 'JavaScript' Files
# Version: 0.1.0
# Authors@R: c( person("Stephane", "Laurent", , "laurent_step@outlook.fr", role = c("aut", "cre")), person("Anton", "Kovalyov", role = "cph", comment = "'jshint' library") )
# Maintainer: Stephane Laurent <laurent_step@outlook.fr>
# Description: Allow to run 'jshint' on 'JavaScript' files with a 'R' command or a 'RStudio' addin. The report appears in the 'RStudio' viewer pane.
# License: GPL-3
# URL: https://github.com/stla/jshintr
# BugReports: https://github.com/stla/jshintr/issues
# Imports: htmltools, htmlwidgets, rstudioapi, tools
# Encoding: UTF-8
# RoxygenNote: 7.2.0
# NeedsCompilation: no
# Packaged: 2022-06-10 09:20:00 UTC; SDL96354
# Author: Stephane Laurent [aut, cre], Anton Kovalyov [cph] ('jshint' library)
# Repository: CRAN
# Date/Publication: 2022-06-10 14:40:02 UTC
